name: superque
version: '1.0.0'
config-version: 2

profile: superque

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  superque:
    staging:
      +materialized: view
      +schema: silver
    dw:
      +materialized: table
      +schema: gold
